version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '127.0.0.1:4566:4566'            # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559'  # external services port range
      - '127.0.0.1:8080:8080'
    environment:
      - SERVICES=s3,sqs,elasticsearch
      - DEBUG=1
      - DEFAULT_REGION=eu-west-2
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock      
      #- DATA_DIR=/tmp/localstack/data
      #- CLEAR_TMP_FOLDER=0
    volumes:
      - './.localstack:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
