AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  jnccwebsitesearchingesterjava:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'search.ingester.Ingester::handleRequest'
      Runtime: java8
      CodeUri: ../elasticsearch-lambda-ingester/target/elasticsearch-lambda-ingester-0.10.0.jar
      Description: ''
      MemorySize: 1024
      Timeout: 300
      Role: 'none'
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue: !GetAtt arn:aws:sqs:elasticmq:000000000000:test-search-queue
            BatchSize: 1
      Environment:
        Variables:
          ES_DOCTYPE: _doc
          ES_ENDPOINT: http://localhost:4571/test-index
          ES_MAX_PAYLOAD_SIZE: '10485760'
      Tags:
        Project: jncc-website-search
      ReservedConcurrentExecutions: 30
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
