AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  jncc-search-deleter

  SAM Template for local dev
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  JnccSearchDeleterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Events:
        SearchEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  JnccSearchApi:
    Description: "API Gateway endpoint URL for Prod stage for jncc-search-deleter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
  JnccSearchFunction:
    Description: "jncc-search-frontend Lambda Function ARN"
    Value: !GetAtt JnccSearchDeleterFunction.Arn
  JnccSearchFunctionIamRole:
    Description: "Implicit IAM Role created for jncc-search-frontend function"
    Value: !GetAtt JnccSearchDeleterFunctionRole.Arn
