version: 0.2

phases:
  build:
    commands:
      - cd jncc-search
      - sam build
      # Copy deployment spec files into the output artifact so we dont have
      # multiple artifacts going into the final stage
      - mkdir .aws-sam/build/JnccSearchFunction/deployment
      - cp deployment/*.yml .aws-sam/build/JnccSearchFunction/deployment
artifacts:
  files:
    - '**/*'
  base-directory: jncc-search/.aws-sam/build/JnccSearchFunction